authentication:
  remember-me:
    key: ${REMEMBER_ME_KEY}
    expiration: 604 800 # 7 days

server:
  port: 8484
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_schema: ${DATABASE_SCHEMA}
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    default-schema: ${DATABASE_SCHEMA}
    liquibase-schema: liquibase
cors:
  allowed-origins: ${FRONTEND_URL}
logging:
  level:
    app.core: ${LOG_LEVEL}
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
      base-path: /internal
  endpoint:
    health:
      show-details: when_authorized
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED}
