authentication:
  remember-me:
    key: ${REMEMBER_ME_KEY}
    expiration: 604 800 # 7 days

server:
  port: 8484
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        default_schema: ${DATABASE_SCHEMA}
      show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:/db/master.xml
    default-schema: ${DATABASE_SCHEMA}
    liquibase-schema: liquibase
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
  web:
    locale: en_US
    locale-resolver: accept_header
cors:
  allowed-origins: ${FRONTEND_URL}
logging:
  level:
    app.core: ${LOG_LEVEL}

management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS}
      base-path: /internal
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    enabled: ${API_DOCS_ENABLED}
    tagsSorter: alpha
    #TODO: low-prio: сортировка для методов не работает
    #TODO: low-prio: не работает интерполяция строк в @schema (dto)
    operations-sorter: method
  api-docs:
    enabled: ${API_DOCS_ENABLED}
    resolve-schema-properties: true