authentication:
  enabled: true
  remember-me:
    key: ${REMEMBER_ME_KEY}
    expiration: 604 800 # 7 days
  hide-usernotfound-exceptions: false

server:
  port: 8484
frontend:
  url: &frontUrl ${FRONTEND_URL}
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
cors:
  allowed-origins: *frontUrl
logging:
  level:
    app.core: ${LOG_LEVEL}
    org.springframework.security.web.authentication.rememberme: ${LOG_LEVEL}