authentication:
  enabled: true
  remember-me:
    key: ${REMEMBER_ME_KEY}
    expiration: 604 800 # 7 days

server:
  port: 8484
spring:
  application:
    name: financial-control
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
cors:
  allowed-origins: ${FRONTEND_URL}
logging:
  level:
    app.core: ${LOG_LEVEL}
