volumes:
  data:

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT:-8484}:8484
    environment:
      DATABASE_URL: ${DATABASE_URL?}
      DATABASE_USERNAME: ${DATABASE_USERNAME?}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD?}
      REMEMBER_ME_KEY: ${REMEMBER_ME_KEY?}
      LOG_LEVEL: ${LOG_LEVEL?}
      FRONTEND_URL: ${FRONTEND_URL?}
      SPRING_PROFILES_ACTIVE: ${ENV?}
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    ports:
      - ${FRONTEND_PORT:-3000}:3000
  postgres:
    image: postgres:14.7
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME?}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD?}
      POSTGRES_DB: financial
    ports:
      - ${DATABASE_PORT:-5432}:5432
    volumes:
      - data:/var/lib/postgresql/data
